/**
 * @file webui.c
 * @brief Встроенная страница интерфейса браузера PS5 (PKG Library, поиск, инсталляция, мониторинг).
 */

#include "webui.h"

const char UI_HTML[] =
#ifdef TEST_ONLY
"<!DOCTYPE html><html><head><meta charset=utf-8>"
"<title>PKG Sender (test build)</title></head>"
"<body style='background:#101418;color:#eee;font-family:sans-serif;"
"display:flex;align-items:center;justify-content:center;min-height:100vh'>"
"<h2>PKG Sender receiver — TEST BUILD, installs disabled</h2>"
"</body></html>";
#else
"<!DOCTYPE html><html><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>PKGri</title>"
"<link rel=icon type='image/png' href='/logo.png'>"
"<style>body{background:#171717;color:#F1F3F8;font-family:'Segoe UI',sans-serif;margin:0;padding:24px;font-size:19px}"
".wrap{max-width:1100px;margin:0 auto}"
".hd{display:flex;align-items:center;gap:10px;margin-bottom:6px;flex-wrap:wrap}"
".hd h2{margin:0;font-size:26px;flex:1}"
".hd #ver{font-size:12px;color:#8B93A5}"
".hd #pcstat{font-size:12px;color:#6FCF7B;background:#202020;border:1px solid #2A2A2A;border-radius:12px;padding:6px 12px;white-space:nowrap;cursor:pointer}"
"#space{font-size:13px;color:#8B93A5;background:#202020;border:1px solid #2A2A2A;border-radius:10px;padding:8px 14px;margin:4px 0 14px;line-height:1.4}"
"#qbar{height:8px;background:#2A2A2A;border-radius:4px;margin-top:8px;display:none;overflow:hidden}"
"#qfill{height:100%;width:0;background:#4F8EF7;border-radius:4px}"
"button:focus-visible,input:focus-visible,.card:focus{outline:3px solid #4F8EF7;outline-offset:2px}"
".card{cursor:pointer}"
"#pcrow{display:flex;gap:8px;margin-bottom:12px;align-items:center;flex-wrap:wrap}"
"#pcrow input{padding:12px;font-size:16px}"
"#pcrow button.go,#pcrow button.gh{padding:12px 16px;font-size:16px}"
"#tools{display:flex;gap:8px;margin-bottom:14px;flex-wrap:wrap}"
"#tools input{flex:1}"
"#chips{display:flex;gap:6px}"
"#chips button{padding:16px 20px;background:#2A2A2A;border:none;border-radius:6px;color:#F1F3F8;font-size:19px;cursor:pointer}"
"#chips button.on{background:#4F8EF7;color:#171717}"
"input{flex:1;padding:16px;border:1px solid #2A2A2A;border-radius:6px;background:#2A2A2A;color:#F1F3F8;font-size:19px}"
"button.go{padding:16px 22px;background:#4F8EF7;border:none;border-radius:6px;color:#171717;font-size:19px;font-weight:bold;cursor:pointer}"
"button.gh{padding:14px 20px;background:#404040;border:none;border-radius:6px;color:#F1F3F8;font-size:19px;cursor:pointer}"
"#grid{display:grid;grid-template-columns:repeat(5,1fr);gap:16px}"
"@media(max-width:1100px){#grid{grid-template-columns:repeat(auto-fill,minmax(180px,1fr))}}"
".card{background:#202020;border-radius:14px;padding:14px;text-align:center;transition:transform .12s,box-shadow .12s;display:flex;flex-direction:column;position:relative}"
".card:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.6)}"
".card img{width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:12px;background:#242424;display:block;box-shadow:0 4px 12px rgba(0,0,0,.35)}"
".card img.cov5,.card img.cov4{border-radius:12px}"
".cov{width:100%;aspect-ratio:1/1;min-height:170px;background:#242424;border-radius:12px;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 12px rgba(0,0,0,.35)}"
".cov.cov5,.cov.cov4{border-radius:12px}"
".cov span{font-size:56px;opacity:.35}"
".badges{position:absolute;top:30px;left:24px;display:flex;gap:6px}"
".bdg{font-size:11px;font-weight:bold;border-radius:4px;padding:2px 8px}"
".card .t{font-size:18px;margin:10px 0 4px;min-height:44px}"
".card .m{font-size:14px;color:#8B93A5;margin-bottom:10px;line-height:1.35;min-height:38px}"
".card button{width:100%;padding:15px;background:#4F8EF7;border:none;border-radius:6px;color:#171717;font-size:19px;font-weight:bold;cursor:pointer;margin-top:auto}"
".card .fc{margin-bottom:10px}"
".card.sel{outline:2px solid #4F8EF7}"
".movl{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.88);z-index:9999}"
".mbox{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#202020;border:1px solid #4F8EF7;border-radius:12px;width:560px;max-width:calc(100% - 40px);max-height:calc(100% - 40px);overflow-y:auto;padding:20px;box-shadow:0 12px 40px rgba(0,0,0,.7);z-index:10000}"
".mbox h3{margin:0 0 4px;font-size:22px;padding-right:52px}"
".mx{position:absolute;top:12px;right:12px;width:44px;height:44px;font-size:24px;line-height:1;background:#2A2A2A;border:none;border-radius:8px;color:#F1F3F8;cursor:pointer}"
".mbox .mm{font-size:14px;color:#8B93A5;margin-bottom:12px}"
".mbox button.go{width:100%;margin-bottom:8px}"
".mclose{width:100%;padding:12px;background:#2A2A2A;border:none;border-radius:6px;color:#F1F3F8;font-size:16px;cursor:pointer;margin-top:4px}"
".fc{display:inline-block;font-size:15px;color:#4F8EF7;border:1px solid #4F8EF7;border-radius:12px;padding:4px 12px;margin-top:6px}"
".fambox{margin-top:8px;display:flex;flex-direction:column;gap:8px}"
".famgrp{font-size:12px;font-weight:bold;color:#8B93A5;padding:8px 12px 4px;text-align:left}"
".member{display:flex;gap:10px;align-items:center;background:#171717;border-radius:10px;padding:14px;text-align:left}"
".member .t{font-size:17px}.member .m{font-size:14px;color:#8B93A5;line-height:1.35}"
".member div:first-child{flex:1}"
".rb{font-size:13px;color:#171717;background:#4F8EF7;border-radius:4px;padding:3px 8px;margin-right:8px}"
".member button{padding:13px 20px;background:#4F8EF7;border:none;border-radius:6px;color:#171717;font-size:18px;font-weight:bold;cursor:pointer}"
"#msg{margin-top:16px;font-size:19px;color:#8B93A5;min-height:30px}"
"#msg.ok{color:#34B595}#msg.err{color:#E17B7B}</style></head><body><div class=wrap>"
"<div class=hd><img src='/logo.png' alt='logo' style='height:44px;width:auto;border-radius:8px'><h2>PKGri</h2><span id=ver>page ...</span><button id=pcstat>PC: ...</button></div>"
"<div id=space style='display:none'></div>"
"<div id=pcrow style='display:none'>"
"<input id=pc placeholder='PC address'><button class=go id=save>Save</button><button class=gh id=reload>Refresh</button></div>"
"<div id=tools><input id=q placeholder='Search title or ID...'>"
"<div id=chips><button data-p=all class=on>All</button><button data-p=PS5>PS5</button><button data-p=PS4>PS4</button></div></div>"
"<div id=msg></div><div id=qbar><div id=qfill></div></div><div id=grid></div>"
"</div><div id=movl style='display:none'><div class=mbox id=mbox></div></div><script>(function(){var PAGE_BUILD='" RECEIVER_BUILD "';"
"var verd=document.getElementById('ver');"
"verd.textContent='page '+PAGE_BUILD+' • receiver …';"
"fetch('/api/version').then(function(r){return r.text();}).then(function(t){"
"if(t.charAt(0)!=='{'){verd.textContent='page '+PAGE_BUILD+' • receiver: unknown (old payload? resend ELF)';return;}"
"var j=JSON.parse(t);"
"verd.textContent='page '+PAGE_BUILD+' • receiver '+j.build+((j.build===PAGE_BUILD)?'':' • MISMATCH — resend the newest ELF');"
"}).catch(function(){verd.textContent='page '+PAGE_BUILD+' • receiver: unreachable';});"
"var pcEl=document.getElementById('pc');"
"var pcstat=document.getElementById('pcstat');"
"var grid=document.getElementById('grid');var msg=document.getElementById('msg');"
"var qEl=document.getElementById('q');"
"var all=[],openFam=null,plat='all';"
"var freeBytes=-1;"
"async function loadSpace(){var sp=document.getElementById('space');"
"try{var r=await fetch('/api/space');var j=await r.json();"
"if(j.free>=0){freeBytes=j.free;var t='Internal: Free '+fmtSize(j.free)+' / '+fmtSize(j.total);"
"if(j.usb&&j.usb.length>0){for(var i=0;i<j.usb.length;i++){t+=' • '+j.usb[i].name+': Free '+fmtSize(j.usb[i].free)+' / '+fmtSize(j.usb[i].total);}}"
"sp.textContent=t;sp.style.display='';}}"
"catch(ex){sp.style.display='none';}}"
"function qTotal(q){var t=0;for(var i=0;i<q.length;i++)t+=(q[i].size||0);return t;}"
"function setBar(done,total){var b=document.getElementById('qbar'),f=document.getElementById('qfill');"
"if(total>0){b.style.display='';f.style.width=Math.min(100,Math.floor(done*100/total))+'%';}else b.style.display='none';}"
"pcEl.value=localStorage.getItem('pri_pc')||'';"
"function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');}"
"function fmtSize(n){if(typeof n!=='number'||isNaN(n)||n<=0)return '0 B';if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';"
"if(n<1073741824)return (n/1048576).toFixed(1)+' MB';return (n/1073741824).toFixed(2)+' GB';}"
"function gameSize(g){if(typeof g.size==='number'&&g.size>0)return fmtSize(g.size);if(g.sizeText&&g.sizeText!=='0.0 GB')return g.sizeText;if(typeof g.size==='number')return fmtSize(g.size);return g.sizeText||'';}"
"function metaHtml(g){var tid=esc(g.titleId||'');var ver='';"
"if(g.version){var vs=String(g.version).trim();ver=(vs.charAt(0).toLowerCase()==='v'?'':'v')+esc(vs);}"
"var l1='';if(tid&&ver)l1=tid+' &middot; '+ver;else if(tid)l1=tid;else if(ver)l1=ver;"
"var sz=gameSize(g);var out='';"
"if(l1)out+='<div>'+l1+'</div>';"
"if(sz)out+='<div>'+esc(sz)+'</div>';"
"return out||'&nbsp;';}"
"function rank(r){return r==='Patch'?1:(r==='DLC'?2:0);}"
"function lone(g){return (g.familyKey||'').indexOf('FILE:')===0;}"
"function isBase(g){return g.role==='Game'||lone(g);}"
"function matchQ(g){var q=qEl.value.trim().toLowerCase();if(!q)return 1;"
"return (g.title+' '+g.titleId).toLowerCase().indexOf(q)>=0;}"
"function matchP(g){if(plat==='all')return 1;return g.platform===plat;}"
"function sortGames(a,b){var pa=a.platform==='PS5'?0:(a.platform==='PS4'?1:2);var pb=b.platform==='PS5'?0:(b.platform==='PS4'?1:2);if(pa!==pb)return pa-pb;var ta=(a.title||'').toLowerCase(),tb=(b.title||'').toLowerCase();return ta<tb?-1:(ta>tb?1:0);}"
"async function install(id,name,hasIcon){msg.className='';msg.textContent='Installing '+name+'...';"
"try{var u='http://'+pcEl.value+':9898/pkg/'+encodeURIComponent(id);"
"var q='/install?url='+encodeURIComponent(u)+'&name='+encodeURIComponent(name);"
"if(hasIcon)q+='&icon='+encodeURIComponent('http://'+pcEl.value+':9898/icon/'+encodeURIComponent(id));"
"var r=await fetch(q);"
"var t=await r.text();"
"if(t.indexOf('ok:')===0){msg.className='ok';msg.textContent=t+' — watch the console notifications.';pollBusy(name).then(function(){loadSpace();});}"
"else{msg.className='err';msg.textContent=t;}}catch(ex){msg.className='err';msg.textContent='Error: '+ex;}}"
"async function pollBusy(name){"
"for(var i=0;i<300;i++){await new Promise(function(rs){setTimeout(rs,2000);});"
"try{var s=await fetch('/api/status');var j=await s.json();"
"if(!j.busy){msg.className='ok';msg.textContent='Done: '+name+' — check the console.';return true;}"
"msg.className='';msg.textContent='Installing '+name+'... (active: '+j.active+')';}"
"catch(ex){return true;}}"
"return true;}"
"async function installOne(m){"
"try{var u='http://'+pcEl.value+':9898/pkg/'+encodeURIComponent(m.id);"
"var q='/install?url='+encodeURIComponent(u)+'&name='+encodeURIComponent(m.title);"
"if(m.hasIcon)q+='&icon='+encodeURIComponent('http://'+pcEl.value+':9898/icon/'+encodeURIComponent(m.id));"
"var r=await fetch(q);"
"var t=await r.text();"
"if(t.indexOf('ok:')===0)return true;"
"msg.className='err';msg.textContent='Failed on '+m.title+': '+t;return false;}"
"catch(ex){msg.className='err';msg.textContent='Error on '+m.title+': '+ex;return false;}}"
"async function waitIdle(){"
"for(var i=0;i<600;i++){await new Promise(function(rs){setTimeout(rs,2000);});"
"try{var s=await fetch('/api/status');var j=await s.json();if(!j.busy)return true;}"
"catch(ex){return true;}}"
"return true;}"
"async function installAll(base){"
"closeModal();"
"var fam=famOf(base);"
"var q=[base].concat(fam);"
"var total=qTotal(q);"
"var c='Install '+base.title+' and '+fam.length+' add-on(s)?';"
"if(total>0)c+='\\nTotal size: '+fmtSize(total);"
"if(freeBytes>=0&&total>0)c+=' — console free: '+fmtSize(freeBytes)+(total>freeBytes?' — NOT ENOUGH SPACE!':'');"
"if(!confirm(c))return;"
"var done=0;setBar(0,total);"
"for(var i=0;i<q.length;i++){"
"msg.className='';msg.textContent='Queue '+(i+1)+'/'+q.length+': '+q[i].title+'...'+(total>0?' ('+fmtSize(done)+' of '+fmtSize(total)+' done)':'');"
"if(!(await installOne(q[i]))){setBar(done,total);return;}"
"if(!(await waitIdle())){setBar(done,total);return;}"
"done+=(q[i].size||0);setBar(done,total);}"
"document.getElementById('qbar').style.display='none';"
"msg.className='ok';msg.textContent='Done: '+base.title+' + '+(q.length-1)+' add-ons'+(total>0?' ('+fmtSize(total)+')':'')+' — check the console.';loadSpace();}"
"function famOf(g){var f=all.filter(function(m){return (m.format==='pkg'||!m.format)&&!isBase(m)&&m.familyKey===g.familyKey;});"
"f.sort(function(a,b){return rank(a.role)-rank(b.role);});return f;}"
"function openModal(g){"
"var box=document.getElementById('mbox');box.innerHTML='';"
"var xx=document.createElement('button');xx.className='mx';xx.textContent='X';"
"xx.onclick=closeModal;box.appendChild(xx);"
"var meta=metaHtml(g);"
"var h=document.createElement('h3');h.textContent=g.title;box.appendChild(h);"
"var mm=document.createElement('div');mm.className='mm';mm.innerHTML=meta+'<div style=\"margin-top:6px\">'+platBadge(g.platform)+'</div>';box.appendChild(mm);"
"var fam=famOf(g);"
"var ib=document.createElement('button');ib.className='go';ib.textContent='Install game';"
"ib.onclick=function(){install(g.id,g.title,g.hasIcon);};box.appendChild(ib);"
"if(fam.length){"
"var ab=document.createElement('button');ab.className='go';ab.style.background='#34B595';"
"ab.textContent='Install all ('+(fam.length+1)+' packages)';"
"ab.onclick=function(){installAll(g);};box.appendChild(ab);"
"var patches=fam.filter(function(m){return m.role==='Patch';});"
"var dlcs=fam.filter(function(m){return m.role!=='Patch';});"
"var fbox=document.createElement('div');fbox.className='fambox';"
"function grp(t,arr){if(!arr.length)return;var hh=document.createElement('div');hh.className='famgrp';hh.textContent=t+' ('+arr.length+')';fbox.appendChild(hh);arr.forEach(function(m){fbox.appendChild(card(m,1));});}"
"grp('Patches',patches);grp('DLC',dlcs);box.appendChild(fbox);}"
"var cb=document.createElement('button');cb.className='mclose';cb.textContent='Close';"
"cb.onclick=closeModal;box.appendChild(cb);"
"document.getElementById('movl').style.display='';"
"document.body.style.overflow='hidden';"
"setTimeout(function(){var x=document.querySelector('#mbox .mx');if(x)x.focus();},50);}"
"function closeModal(){document.getElementById('movl').style.display='none';document.body.style.overflow='';}"
"function platBadge(p){if(p==='PS5')return '<span class=bdg style=\"background:#F1F3F8;color:#171717\">PS5</span>';if(p==='PS4')return '<span class=bdg style=\"background:#0070D1;color:#fff\">PS4</span>';return '';}"
"function covCls(g){return g.platform==='PS4'?'cov4':'cov5';}"
"function card(g,sub){var d=document.createElement('div');d.className=sub?'member':'card';"
"var im=(!sub)?(g.hasIcon?'<img class=\"'+covCls(g)+'\" src=\"http://'+pcEl.value+':9898/icon/'+encodeURIComponent(g.id)+'\">':'<div class=\"cov '+covCls(g)+'\"><span>🎮</span></div>'):'';"
"var meta=metaHtml(g);"
"var badge=sub?(g.role==='Patch'?'<span class=rb style=\"background:#E17B7B\">Patch</span>':(g.role==='DLC'?'<span class=rb style=\"background:#E8A34C\">DLC</span>':'<span class=rb>'+esc(g.role)+'</span>')):'';"
"if(sub){d.innerHTML='<div><div class=t>'+esc(g.title)+'</div><div class=m>'+meta+'</div></div>';"
"var w=document.createElement('div');w.innerHTML=badge;"
"var b=document.createElement('button');b.textContent='Install';"
"b.onclick=function(ev){ev.stopPropagation();install(g.id,g.title,g.hasIcon);};"
"w.appendChild(b);d.appendChild(w);return d;}"
"var fam=famOf(g);"
"var cnt=fam.length?'<span class=fc>'+fam.length+' add-on'+(fam.length>1?'s':'')+'</span>':'';"
"var pb=platBadge(g.platform);"
"d.innerHTML=im+'<div class=t>'+esc(g.title)+'</div><div class=m>'+meta+'</div>'+(pb?'<div class=badges>'+pb+'</div>':'')+cnt;"
"var btn=document.createElement('button');btn.textContent='Install';"
"btn.onclick=function(ev){ev.stopPropagation();install(g.id,g.title,g.hasIcon);};"
"d.onclick=function(){openModal(g);};"
"d.appendChild(btn);"
"d.tabIndex=0;"
"d.onkeydown=function(ev){if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();d.click();}};"
"return d;}"
"function render(){grid.innerHTML='';var list=all.filter(function(g){return (g.format==='pkg'||!g.format)&&isBase(g)&&matchP(g)&&matchQ(g);});"
"list.sort(sortGames);"
"if(!list.length){msg.textContent=all.length?'No match.':'Library is empty — tick Publish library in PKG Sender.';return;}"
"msg.textContent=list.length+(list.length===1?' game':' games');"
"list.forEach(function(g){grid.appendChild(card(g,0));});}"
"document.getElementById('movl').onclick=function(ev){if(ev.target.id==='movl')closeModal();};"
"document.addEventListener('keydown',function(ev){if(ev.key==='Escape')closeModal();});"
"async function resolvePc(){"
"try{var r=await fetch('/api/pc');var j=await r.json();"
"if(j.pc&&j.age>=0&&j.age<15){pcEl.value=j.pc;pcstat.textContent='PC: '+j.pc+' (auto)';return j.pc;}}catch(e){}"
"var m=(pcEl.value||localStorage.getItem('pri_pc')||'').trim();"
"if(m){pcEl.value=m;pcstat.textContent='PC: '+m+' (manual)';return m;}"
"pcstat.textContent='PC: ?';return '';}"
"async function load(){var pc=await resolvePc();"
"if(!pc){msg.textContent='No PC found — tick Publish library in PKG Sender, or type the PC address.';document.getElementById('pcrow').style.display='';return;}"
"localStorage.setItem('pri_pc',pc);msg.textContent='Loading...';grid.innerHTML='';all=[];"
"try{var r=await fetch('http://'+pc+':9898/catalog');"
"all=await r.json();openFam=null;render();loadSpace();}"
"catch(ex){msg.textContent='Error: '+ex+' — is Publish library on and the PC reachable?';}}"
"document.getElementById('save').onclick=load;"
"document.getElementById('reload').onclick=load;"
"document.getElementById('pcstat').onclick=function(){var r=document.getElementById('pcrow');r.style.display=(r.style.display==='none')?'':'none';};"
"pcEl.onkeydown=function(ev){if(ev.key==='Enter')load();};"
"qEl.oninput=render;"
"var chips=document.getElementById('chips').children;"
"for(var i=0;i<chips.length;i++)(function(c){c.onclick=function(){plat=c.getAttribute('data-p');"
"for(var k=0;k<chips.length;k++)chips[k].className='';c.className='on';render();};})(chips[i]);"
"load();})();</script>"
"</body></html>";
#endif
